#!/system/bin/sh
# shellcheck shell=ksh
# SPDX-License-Identifier: GPL-2.0-or-later

SCRIPT_DIR=$(dirname "$(realpath "$0")")
export SCRIPT_DIR

set -uo pipefail

set -- -t touchscreen -i 0 -- echo {}
source "${SCRIPT_DIR}/iptsd-foreach"

spdlog warn "iptsd-find-hidraw is deprecated, please use iptsd-foreach"
