#!/system/bin/sh
# shellcheck shell=ksh
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail


SCRIPT_DIR=$(dirname "$(realpath "$0")")
export SCRIPT_DIR

set -- -t touchscreen -i 0 -- echo 'iptsd@$(systemd-escape --path "{}").service'
source "${SCRIPT_DIR}/iptsd-foreach"
